// Currency handled by js/currency.js
if(typeof BD!=="undefined")BD.initCurrency();
var C={"Women's Clothing":"[dress]","Home, Garden & Furniture":"[home]","Jewelry & Watches":"[ring]","Automobiles & Motorcycles":"[car]","Health, Beauty & Hair":"[makeup]","Men's Clothing":"[shirt]","Bags & Shoes":"[bag]","Pet Supplies":"[paw]","Toys, Kids & Babies":"[toy]","Home Improvement":"[wrench]","Sports & Outdoors":"[ball]","Phones & Accessories":"[phone]","Consumer Electronics":"[headphones]","Other":"[box]"};
function esc(s){return(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}
var ALL=[],RAW={};
(function load(){
var x=new XMLHttpRequest();
x.open('GET','https://cdn.jsdelivr.net/gh/jamestuwairua77-cpu/bargain-drop-preview@main/categories-data.json',true);
x.onload=function(){if(x.status>=200&&x.status<400){RAW=JSON.parse(x.responseText);var cats=Object.keys(RAW),prods=[];for(var i=0;i<cats.length;i++){var c=cats[i],items=RAW[c]&&RAW[c].products?RAW[c].products:[];for(var j=0;j<items.length;j++){var p=items[j];p._cat=c;p._emoji=C[c]||'[box]';prods.push(p)}}ALL=prods;renderCats(cats);renderProds(prods.slice(0,50))}};
x.send()
})();
function renderCats(cats){var g=document.getElementById('cat-grid');g.innerHTML='';for(var i=0;i<cats.length;i++){var c=cats[i],info=RAW[c]||{},heroes=info.hero_images||[],items=info.products||[],e=C[c]||'[box]';var a=document.createElement('a');a.className='cat-card fade-in';a.href='category.html?cat='+encodeURIComponent(c);var h='';if(heroes.length>0){h='<div class="cat-hero">';for(var j=0;j<4&&j<heroes.length;j++)h+='<img src="'+heroes[j]+'" alt="" loading="lazy"'+(j===0?' style="grid-row:1/3"':'')+'>';h+='</div>'}else{h='<div class="cat-hero"><div style="grid-row:1/3;display:flex;align-items:center;justify-content:center;font-size:3rem;background:#f5f5f5;width:100%;height:100%">'+e+'</div><div style="background:#f5f5f5"></div><div style="background:#f5f5f5"></div><div style="background:#f5f5f5"></div></div>'}a.innerHTML=h+'<div class="cat-card-info"><div class="cc-label">'+esc(c)+'</div><div class="cc-count">'+items.length.toLocaleString()+' products</div></div>';g.appendChild(a)}}
function renderProds(prods){var g=document.getElementById('product-grid');g.innerHTML='';if(!prods.length){g.innerHTML='<div class="loading-text">No products found</div>';return}for(var i=0;i<prods.length;i++){var p=prods[i],img=p.image||(p.images||[])[0]||'';var a=document.createElement('a');a.className='product-card fade-in';a.href='product.html?id='+p.id;var d='';if(p.compare_at_price&&p.compare_at_price>p.price)d='<div class="prod-badge">-'+Math.round((1-p.price/p.compare_at_price)*100)+'%</div>';a.innerHTML='<div class="prod-img">'+d+(img?'<img src="'+img+'" alt="" loading="lazy">':'<div style="font-size:4rem;opacity:.2">'+C.Other+'</div>')+'</div><div class="prod-info"><div class="prod-title">'+esc(p.title)+'</div><div class="prod-price-row"><span class="prod-price">'+BD.formatMoneyCompact(p.price||0)+'</span>'+(p.compare_at_price&&p.compare_at_price>p.price?'<span class="prod-compare">'+BD.formatMoneyCompact(p.compare_at_price)+'</span>':'')+'</div></div>';g.appendChild(a)}}
function doSearch(){var q=document.getElementById('search-input').value.toLowerCase().trim(),clr=document.getElementById('search-clear');clr.style.display=q?'flex':'none';if(q){document.getElementById('cat-section').style.display='none';document.getElementById('trending-title').style.display='none';document.getElementById('search-title').style.display='flex';var results=ALL.filter(function(p){return(p.title||'').toLowerCase().indexOf(q)>=0}).slice(0,50);document.getElementById('search-count').textContent=results.length+' of '+ALL.length+' products';renderProds(results)}else{document.getElementById('cat-section').style.display='';document.getElementById('trending-title').style.display='';document.getElementById('search-title').style.display='none';renderProds(ALL.slice(0,50))}}
function clearSearch(){document.getElementById('search-input').value='';doSearch();document.getElementById('search-input').focus()}
(function(){var c=JSON.parse(localStorage.getItem('bd_cart')||'[]'),cnt=c.reduce(function(s,i){return s+(i.qty||1)},0);var el=document.getElementById('cart-count');if(el)el.textContent=cnt})();